### ISSUE TITLE
set textIsSelectable , select text not work

### ISSUE THREAD

**Issue by taosimple** [SufficientlySecure/html-textview#83] opened 2016-12-25 02:29 UTC
Set textIsSelectable attr on xml, when onLongClick select text not work, It behavior very strange the cursor not show and can't select.

**Comment by dschuermann** [comment] 2017-05-26 20:15
duplicate of https://github.com/SufficientlySecure/html-textview/issues/59

**Closed by dschuermann** 2017-05-26 20:15 UTC
Labels: bug

**Comment by dschuermann** [comment] 2017-05-28 19:46
Please try version 3.4
